### ISSUE TITLE
Connect with the API and start to update Offers based on that

### ISSUE THREAD

**Issue by nachoal** [ArturoEstNav/rails-remotedesk#9]
### API
Check if the JSON brings a status, offer_id (from the API side) that you can store on your BD to know if offer already exists.
Think of a way to know which offers are no longer active.

1. Create the `APISyncJob` (name TBD) that will handle the responsibility of connecting to the API and generating/updating/deactivating the job offers. (Heroku charges 7USD per worker a month)
2. Configure job to be ran at X time each day/hour (decide) and turn it on on heroku to test. 

### Nice to have for learning:

1. Create a Service Object that's going to be called from the job
2. Spec!

**Comment by ArturoEstNav** [comment]
Views to implement: show offer

**Comment by berveco** [comment]
Finished the API work, moving to the syncjob

**Comment by berveco** [comment]
> Views to implement: show offer

Finished show offer mock design. A lot of room for improvement, but works.
